sftp/defaults/main.yml, sftp/handlers/main.yml, sftp/tasks/main.yml
This role creates unpriviliged, shell-less users that only have access to a chrooted environment on the server via sftp. These users are forbidden from opening a login shell via ssh.
=> Add sftp role

logstash/defaults/main.yml, logstash/tasks/main.yml, openjdk/defaults/main.yml, openjdk/tasks/main.yml, openjdk/templates/openjdk.sh
Logstash requires Java to run. The `openjdk` role installs OpenJDK 8 and sets the `JAVA_HOME` environment variable.
=> Add openjdk role

consul_template/tasks/main.yml
This PR removes the shell-out to `docker pull` and uses the `docker_image` module instead. A [bug](https://github.com/ansible/ansible-modules-core/issues/2991) was fixed in Ansible 2.1 that allows `docker_image` to be use for pulling images without having to specify the `path` parameter.
=> Remove workaround for bug in Ansible 2.0

ossec/defaults/main.yml, ossec/handlers/main.yml, ossec/tasks/main.yml, ossec/templates/openssl.cnf, ossec/templates/ossec-authd.service, ossec/templates/preloaded-vars.conf
This PR installs and configures OSSEC either as an agent or a server.
The server runs the `ossec-authd` service, which listens on port 1515 by default and allows agents to register. To configure a machine as a server, you must set `ossec_install_type: "server"`.
When OSSEC runs as an agent, it must register with `ossec_authd` on the server by running the `agent-auth` command. When configuring OSSEC as an agent, you must set `ossec_server_ip` with the IP address of the machine running in server mode.
=> Add OSSEC role

snort/defaults/main.yml, snort/tasks/main.yml, snort/templates/custom.rules, snort/templates/pulledpork.conf, snort/templates/snort.conf
A list of custom snort rules can be specified by setting the `snort_custom_rules` variable. By default, these are inserted into the `custom.rules` template and stored on the remote machine at `/etc/snort/rules/custom.rules`. Custom rules files/templates can be specified by setting `snort_custom_rules_files`.
This PR also allows for setting the Pulled Pork IPS Policy via the `snort_pulledpork_ips_policy` variable. This basically controls which rules are enabled so that different levels of strictness can be used. See the [Pulled Pork docs](https://github.com/shirkdog/pulledpork/blob/master/doc/README.RULESET) for details.
Depends on https://github.com/appsembler/roles/pull/7
=> Allow specifying custom rules for Snort

logstash/defaults/main.yml, logstash/files/snort, logstash/templates/20_snort_filter.conf, logstash/templates/20_ssh_filter.conf, logstash/templates/30_pagerduty_output.conf
This PR makes it possible to parse Snort alert logs and create PagerDuty alerts.
Example configuration to send Snort alerts to PagerDuty:
```
logstash_output_pagerduty_service_key: "{{ secret_logstash_output_pagerduty_service_key }}"
logstash_output_pagerduty_alerts:
- type: "snort"
description: "Snort: %{message} [%{host}]"
incident_key: "snort%{month}%{day}%{message}%{src}%{dest}"
details:
host: "%{host}"
messsage: "%{message}"
protocol: "%{protocol}"
source: "%{src}"
desination: "%{dest}"
```
Alternative to https://github.com/appsembler/roles/pull/11
=> Add logstash configs for snort and pagerduty

gcsfuse/defaults/main.yml, gcsfuse/tasks/main.yml, letsencrypt/defaults/main.yml, letsencrypt/tasks/main.yml, letsencrypt/templates/nginx/letsencrypt
This PR provides the ability to generate TLS certificates for nginx using the [webroot plugin](https://letsencrypt.readthedocs.io/en/latest/using.html#webroot) for Let's Encrypt. The webroot plugin uses the [http-01](https://github.com/ietf-wg-acme/acme/blob/master/draft-ietf-acme-acme.md#user-content-http) challenge and stores challenge response data in the directory specified by `letsencrypt_webroot`.
When generating certificates behind a load balancer, it's necessary for all servers in the pool to have access to the challenge response data. On GCP, [gcsfuse](https://github.com/GoogleCloudPlatform/gcsfuse) can be used to mount a shared Google Storage bucket to the `letsencrypt_webroot` directory.
Example configuration:
```
letsencrypt_webroot: "/var/www/letsencrypt"
letsencrypt_webuser: …
```
=> Add letsencrypt and gcsfuse roles

consul_template/tasks/main.yml, filebeat/defaults/main.yml, filebeat/tasks/main.yml, incron/tasks/main.yml, logstash/defaults/main.yml, logstash/tasks/main.yml, ossec/tasks/main.yml, sftp/tasks/main.yml, snort/tasks/main.yml
- Update syntax for `with_items` (quotes and curlies are now required around variable names)
- Update package repos for filebeat and logstash
- Add defaults for `logstash_output_pagerduty_alerts` and `logstash_output_pagerduty_service_key`, which were missing (a bug!)
=> Updates for Ansible 2.2 and Xenial

monit/defaults/main.yml, monit/templates/hosts, monit/templates/system
This allows us to request URLs to monitor things like static assets.
`monit_check_hosts` is a list of hashes where each hash defines a check. Each hash can optionally specify `host`, `port`, `protocol`, `status`, `request`, and `content`. These are used to configure monit's [`CHECK HOST`](https://mmonit.com/monit/documentation/monit.html#Remote-host) checks. `monit_check_hosts_defaults` can be defined to set default values for each hash in `monit_check_hosts`.
=> Add ability to monitor URLs with monit

.gitignore, snort/defaults/main.yml, snort/tasks/main.yml
Neither one of the packages are being downloaded. Which breaks the build!
Probably we should just update snort, but I'd rather rely on @mrgnr to do it since I'm completely unaware of that thing.
=> Fix Snort/DAQ 404 errors

letsencrypt/defaults/main.yml, letsencrypt/templates/nginx/letsencrypt
If `letsencrypt` is specified in `nginx_default_sites`, it should be there as default_server so that the request for verification when generating a certificate are handled by this nginx config and not the LMS one.
=> Add default_option for letsencrypt nginx template

consul_template/defaults/main.yml
Upgrading consul template to version 0.19.4, this should only affect Wharf as far as I know, but please confirm @OmarIthawi @tkeemon @tomaszzielinski
=> Upgrade consul template to 0.19.4

letsencrypt/defaults/main.yml, letsencrypt/tasks/main.yml
Bcuz of manual runs the log permissions becomes incorrect. This ensures that the process is more robust.
BTW, as long as being run via Ansible the log is created automatically via `$ certbot` in the `Generate certificates using webroot` step with correct permissions.
=> Explicitly set permissions for letsencrypt log

snort/defaults/main.yml
In #19 we've fixed an error because SourceForge started giving 404 on Snort DAC without any notice. The issue came up again today, when the download mirror gave a different sha256sum for the snort tar.gz, which could be a normal update or a security hazard!
Luckily we have the sha256sum, so I Googled and found an alternative. Then, I've created a dummy release tag and uploaded the `.tag.gz` files to it:
- https://github.com/appsembler/roles/releases/tag/v0.1-alpha
=> Self-host snort and DAQ

.travis.yml, Makefile, README.md, tests/inventory, tests/test.yml, tests/travis.yml, travis/Dockerfile.ubuntu-trusty, travis/Dockerfile.ubuntu-xenial
Ansible roles need tests too :)
This sets up a simple testing framework to start with:
* you can now run `make syntax-check` to get a quick syntax check
* TravisCI is enabled and attempts to install the roles on Ubuntu 14.04 and 16.04 instances using ansible 2.4 and 2.3. Then it re-runs the install to check for idempotency violations.
Obviously, this is not very thorough testing. I'm just trying to get something in place so we can add more as we go.
Notes/questions:
* I'd like to get other ansible versions included as well. I tried with 2.2.0.0 (which ficus uses), but there were idempotency problems there. I will dig into those later and see if I can get it added later.
* Do we care about any other OS versions? I know there are still some 12.04 machines out there but I don't think it's a …
=> Add simple tests

letsencrypt/templates/nginx/letsencrypt
This is to support enterprise deployments (non-Tahoe), without having to worry about setting extra variables.
For acme challenges, otherwise it keeps 404'ing. Even when I set the following vars for ASU CSET configs (https://github.com/appsembler/edx-configs/pull/177), even when including Filip's #20:
```
letsencrypt_enable_default_server: yes
nginx_enable_custom_domains: "{{ letsencrypt_enable_default_server }"
```
Which [@bezidejni suggested on Slack](https://appsembler.slack.com/archives/G03M0NWL5/p1510125636000111).
---
=> Explicitly set the domain names for letsencrypt

.gitignore
When testing locally, ansible likes to create files like `tests/travis.retry`. Let's just ignore those.
=> ignore .retry files

consul_template/tasks/main.yml
Just a small change that allows us to template the config file for consul-template. The version of this repo/submodule is pinned in the Wharf repo so merging this won't break anything.
=> Template consul template (instead of copy)

letsencrypt/README.md, letsencrypt/defaults/main.yml, letsencrypt/tasks/main.yml
Because `name: Generate certificates using webroot` only works once in a server life time. 
This is due to `creates: /etc/letsencrypt/live/{{ item.domains[0] }}/fullchain.pem`. Unless you manually delete the `.pem` file or change the domain, it shouldn't run again.
- @bryanlandia more detailed review.
- @thraxil If you're curious.
- @melvinsoft for a light review to ensure we're not breaking anything for Tahoe.
- @bezidejni for a light review to ensure we're not breaking anything for Blue Team.
=> Support LetsEncrypt renew during Ansible provision

.gitignore, .travis.yml
Get ready for the future.
I don't think it's worth it to run the ansible 2.5 tests on Trusty. I imagine that when we actually get to the point of using ansible 2.5, we won't be doing it against anything older than Xenial.
=> test against ansible 2.5

letsencrypt/README.md, letsencrypt/defaults/main.yml, letsencrypt/files/certbot_override.conf, letsencrypt/tasks/main.yml
Major refactoring for the LetsEncrypt role to fix the bugging issues in its renew process: ![](https://github.trello.services/images/mini-trello-icon.png) [(8) Fix the cronjob issue with LetsEncrypt](https://trello.com/c/3cePOzCF/2746-8-fix-the-cronjob-issue-with-letsencrypt). This PR fixes #28.
`certbot` cronjob thinks that `systemd` will do the scheduling, but systemd seems not to be configured to run `$ certbot`. We used a custom cronjob and solved the issue.
- Include and refactor Appsembler's cronjob: https://github.com/appsembler/roles/pull/26
- Require exact `$ certbot` `apt` and `pip` package versions with sanity checks on them.
- Expliclity fail if there are more than one `$ certbot` binary was found.
- Docs
- Use `become_user: root` instead of `become_user: "{{ …
=> Fix certbot cronjob and add checks for the LetsEncrypt role to keep developer's sanity

consul_template/defaults/main.yml, consul_template/templates/consul-template.conf
On several wharf servers, potentially connected to upgrading of consul-template image, I've been getting errors like these in the logs:
```
Jun 22 17:10:22 staging-appsembler-wharf-0 docker[20194]: 2018/06/22 17:10:22.838711 [ERR] (cli) 1 error occurred:
Jun 22 17:10:22 staging-appsembler-wharf-0 docker[20194]: * failed to execute command "/bin/true" from "/etc/consul-template/templates/containers.conf" => "/etc/consul-template/rend
Jun 22 17:10:23 staging-appsembler-wharf-0 systemd[1]: consul-template.service: Main process exited, code=exited, status=14/n/a
Jun 22 17:10:23 staging-appsembler-wharf-0 docker[20580]: consul-template
Jun 22 17:10:23 staging-appsembler-wharf-0 systemd[1]: consul-template.service: Unit entered failed state.
Jun 22 17:10:23 staging-appsembler-wharf-0 …
```
=> Make consul template command optional

letsencrypt/defaults/main.yml, letsencrypt/tasks/main.yml
0.22.2 is no longer in the apt repo (at least on Tahoe 16.04 servers), so it fails when attempting to update.
=> bump letsencrypt version to 0.25.0

cert_agent/defaults/main.yml, cert_agent/templates/cert_agent.service
By default Gunicorn timeout is 30 seconds, that isn't enough for the custom domains generation process. This PR adds the variable to the service definition, we keep 30 sec in the default, but we're increasing this a lot in the companion edx-configs PR: https://github.com/appsembler/edx-configs/pull/416
=> Allow setting gunicorn timeout

cert_agent/defaults/main.yml
allow the various statsd environment variables to be set via ansible. Mostly, this is so we can set the `STATSD_HOST` correctly in production.
=> configure statsd settings for cert_agent

letsencrypt/tasks/main.yml
in case we need to add or remove a domain from existing cert before renewal is due
This will only recreate the certificate if the domains have changed.
=> LetsEncrypt Always check for modifications

letsencrypt/defaults/main.yml
=> LetsEncrypt 0.26.x no longer available in certbot PPA... update to 0.28.0

letsencrypt/defaults/main.yml
As usual, they have removed the old certbot version (0.28.0) from the PPA so deploys fail. Time to bump the version.
=> certbot 0.31.0

google-fluentd/templates/apt_history.conf, google-fluentd/templates/authlog.conf, google-fluentd/templates/edx_edxapp.conf, google-fluentd/templates/edx_nginx_json.conf, google-fluentd/templates/edx_supervisord.conf, google-fluentd/templates/edx_tracking.conf, google-fluentd/templates/kernlog.conf, google-fluentd/templates/letsencrypt.conf
Trying to get config files for all of the common services we actually use to parse their custom log formats.
For this batch, I went through the logs on a ficus edxapp server. So this gets all the LMS/CMS logs, tracking logs, supervisord logs, plus some common ones like `auth.log`, `kern.log`, `apt/history.log`, and
letsencrypt logs.
Some of these could definitely be better as far as parsing out all of the fields. This first pass mostly just tries to get them all captured so we can do basic searching in stackdriver without worrying too much
about being able to precisely filter on every field.
The playbook deploying this role will need to specify which of these configs should be deployed and enabled with the `google_fluent_custom_config_files` and `google_fluent_custom_config_templates` …
=> add fluentd config files for more services

letsencrypt/templates/nginx/letsencrypt
if there are no letsencrypt_certs, it should skip setting the `server_name` altogether instead of producing a line like `server_name ;` which breaks nginx.
Normally, this shouldn't be an issue, but I've been running into it as I work on Tahoe Hawthorn, since I have to skip the custom domains role sometimes and that leaves the `letsencrypt` role with an empty `letsencrypt_certs` list and the bad nginx config, which I then have to manually delete after each deploy.
=> avoid generating invalid letsencrypt nginx config

cert_agent/tasks/main.yml
Enable it so it will be started automatically when the server boots. Also ensure that the service is started as part of the deploy.
(also fix a misleading task name that was next to it)
=> enable cert_agent systemd service on boot

fix_dir_perms/defaults/main.yml, fix_dir_perms/meta/main.yml, fix_dir_perms/tasks/main.yml, tests/test.yml, tests/travis.yml
Tahoe has a problem with conflicts between roles. `gcsfuse` creates `/var/www/letsencrypt`, which implicitly creates `/var/www` if it doesn't already exist. `nginx` creates `/var/www` but because we do other things in that role, in Tahoe's case it needs to run after gcsfuse. That leads to incorrect permissions/ownership on `/var/www`. We can't fix the ownership in the gcsfuse role because it runs potentially before nginx has created the user that it needs. The cleanest solution I could come up with (without completely refactoring our entire deployment) is to add a very simple utility role that we can run after both of them to fix up the permissions.
=> add role for fixing directory permissions

letsencrypt/defaults/main.yml, letsencrypt/tasks/main.yml
Cronjob to remove old certificate, key, and CSR files. Disabled by default.
Letsencrypt certificates are at most 90 days old. Any certificates, keys, or CSR files more than 90 days old are useless (and we default to only deleting after 180 days to be extra safe).
The files are very small and most of the time it isn't worth worrying about them. However, in Tahoe's case, since per-file access on the GCS Fuse mount is expensive, it matters at times. Specifically, tarring and untarring the `/etc/letsencrypt` directory for the ficus -> hawthorn upgrade touches every file in there. Checking on Tahoe staging, there are currently 1223 of these old files (more than 180 days old). It's about 1 second per file to read or write. That means that the process of making a tarball spends over 1200 seconds …
=> letsencrypt cleanup task

letsencrypt/tasks/main.yml
It's broken otherwise as of https://github.com/appsembler/roles/pull/61:
```
Step #15 - "build and run ax/ansible": TASK [../../appsembler-roles/letsencrypt : Create a cleanup cronjob to clear old key and csr files] ***
Step #15 - "build and run ax/ansible": fatal: [35.185.107.18]: FAILED! => {"changed": false, "failed": true, "msg": "Unsupported parameters for (cron) module: tags,when. Supported parameters include: backup,cron_file,day,disabled,env,hour,insertafter,insertbefore,job,minute,month,name,reboot,special_time,state,user,weekday"}
Step #15 - "build and run ax/ansible": fatal: [35.196.92.71]: FAILED! => {"changed": false, "failed": true, "msg": "Unsupported parameters for (cron) module: tags,when. Supported parameters include: …
```
=> Fixup for the broken certs cleanup tasks

cert_agent/defaults/main.yml
The playbook it runs when adding a new custom domain. This is now dedicated (since it needs a slightly different order).
See: https://github.com/appsembler/configuration/pull/237 (it will need that one to be merged before this is safe to deploy)
=> configure cert agent to use a dedicated playbook

tests/test.yml
not quite ready to delete the role (redeploying an old deployment may need it, but it will be safe once we have everything on hawthorn or later). But we might as well save a few seconds and skip it in the tests.
=> monit is no longer used

letsencrypt/tasks/main.yml
I ran into a situation where, during a deploy, the "Generate certificates using webroot" task runs when one or more of the certs already exists and it goes into an interactive mode, breaking the ansible deploy:
```
Cert not yet due for renewal
You have an existing certificate that has exactly the same domains or certificate name you requested and isn't close to expiry.
(ref: /etc/letsencrypt/renewal/lms-hawthorn.sandbox.customer.appsembler.com.conf)
What would you like to do?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: Keep the existing certificate for now
2: Renew & replace the cert (limit ~5 per 7 days)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-2] then [enter] (press 'c' to …
```
=> make sure certbot runs non-interactively

.travis.yml, gcsfuse/tasks/main.yml, travis/Dockerfile.ubuntu-bionic
Since we dropped Trusty, I figured it's about time we start thinking about the future. This adds 18.04 to our tests (only with the newer ansible release though since any new 18.04 based systems we set up we ought to be able to restrict to newer ansible releases; ansible 2.3 will be the next thing to work on phasing out).
Of the existing roles, it did uncover one issue with `gcsfuse`, which is that it was installing the APT repo before installing the key for that repo. I think on older releases, nothing was actually verified until you actually did an `apt-get install` but from 18.04 forward, it checks the key when you add the repo, so those steps needed to be reversed in the playbook.
=> Test on bionic

scriabin/README.md, scriabin/defaults/main.yml, scriabin/files/scriabin.py, scriabin/tasks/main.yml, scriabin/templates/run_scriabin.sh.j2, tests/test.yml, tests/travis.yml, travis/Dockerfile.ubuntu-bionic
https://appsembler.atlassian.net/browse/OT-293
scriabin is a stopgap script that watches our nginx logs and pushes the metrics to prometheus via a pushgateway.
We would prefer a pull-based approach (see
https://appsembler.atlassian.net/wiki/spaces/ED/pages/43614296/Getting+Data+into+P
rometheus) but we don't have that set up yet.
Scriabin works very simply by running once per minute in a cron job. It parses JSON formatted nginx logs (using Pygtail to track file offsets between runs) and submits the summarized metrics to
Prometheus.
This role should be installed on edxapp servers and, with a regular config, all the default values should work.
The code for this role is taken almost directly from `infrastructure`, where it was created and where it's been used for Tahoe, etc. for a while now. …
=> add scriabin role

scriabin/defaults/main.yml, scriabin/files/scriabin.py, scriabin/tasks/main.yml
This lets it work on servers not set to UTC.
Apparently some of our deployments use a different TZ setting. Nginx's log config will only log times in the local TZ (AFAICT, you can't configure it to log in UTC if the server isn't).
The log format that nginx uses also doesn't match up to `strptime()`s `%z` pattern for matching the timezone. Eg, nginx will write it with `-07:00` where `%z` would only match on `-0700`.
So one option is to hard-code the time zone in the format string, setting that on any non-UTC servers (as in the previous version) so `strptime()` can parse it and compare it to the current time in UTC.
The simpler solution implemented here is to just use `python-dateparser`, which can handle the nginx timestamps properly (but gives you a local time) and compare that to a local …
=> scriabin: use dateutil to parse local times
